### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/festool-oberfraese-einweisung#1]
Warum ist denn die Lizenz ungeklärt? Sie sollte unbedingt `CC BY-SA 3.0` sein.

**Comment by Virtex7** [comment]
die lizenz ist aktuell cc by sa, aller text stammt von mir und ist so zu
lizensieren.
der Hinweis muss aus der Einweisung stammen, aus der ich das Template
genommen habe.

**Comment by sedrubal** [comment]
:+1:
